export const items = [
  {
    id: '1',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'דייסה',
    status: { label: 'lowstock', labelValue: 'אזהרה' },
  },
  {
    id: '2',
    numOfUnits: 6,
    minimumForAlert: 4,
    name: 'אבטיח',
    status: { label: 'stock', labelValue: ' במלאי' },
  },
  {
    id: '3',
    numOfUnits: 0,
    minimumForAlert: 4,
    name: 'במבה',
    status: { label: 'outofstock', labelValue: ' לא במלאי' },
  },
  {
    id: '4',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'גזר',
    status: { label: 'lowstock', labelValue: 'אזהרה' },
  },

  {
    id: '5',
    numOfUnits: 0,
    minimumForAlert: 4,
    name: 'חלב טבעוני',
    status: { label: 'outofstock', labelValue: 'לא במלאי' },
  },
  {
    id: '6',
    numOfUnits: 3,
    minimumForAlert: 4,
    name: 'חלב טבעוני',
    status: { label: 'lowstock', labelValue: 'אזהרה' },
  },
  {
    id: '1',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'דייסה',
    status: { label: 'lowstock', labelValue: 'אזהרה' },
  },
  {
    id: '2',
    numOfUnits: 6,
    minimumForAlert: 4,
    name: 'אבטיח',
    status: { label: 'stock', labelValue: ' במלאי' },
  },
  {
    id: '3',
    numOfUnits: 0,
    minimumForAlert: 4,
    name: 'במבה',
    status: { label: 'outofstock', labelValue: ' לא במלאי' },
  },
  {
    id: '4',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'גזר',
    status: { label: 'lowstock', labelValue: 'אזהרה' },
  },

  {
    id: '5',
    numOfUnits: 0,
    minimumForAlert: 4,
    name: 'חלב טבעוני',
    status: { label: 'outofstock', labelValue: 'לא במלאי' },
  },
  {
    id: '6',
    numOfUnits: 3,
    minimumForAlert: 4,
    name: 'חלב טבעוני',
    status: { label: 'lowstock', labelValue: 'אזהרה' },
  },
];
