export const items = [
  {
    id: '1',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'אבטיח',
  },
  {
    id: '2',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'במבה',
  },
  {
    id: '3',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'גזר',
  },
  {
    id: '4',
    numOfUnits: 1,
    minimumForAlert: 4,
    name: 'דייסה',
  },
  {
    id: '5',
    numOfUnits: 3,
    minimumForAlert: 4,
    name: 'חלב טבעוני',
  },
  {
    id: "6",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "7",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "8",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "9",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "10",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "11",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "12",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "13",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "14",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
  {
    id: "15",
    numOfUnits: 3,
    minimumForAlert: 4,
    name: "חלב טבעוני",
  },
];
