export const enum Strings {
  SearchBarPlaceholder = 'חיפוש...(ניתן לחפש לפי שם המוצר, סוג המוצר)',
  UnitInInventory = "יח' במלאי:",
  UnitBeforeWarning = 'יח׳ לפני אזהרה:',
  DashboardCardTitleItems = 'מוצרים',
  DashboardCardTitleTotalInventory = 'סה״כ מלאי',
  DashboardCardTitleWeeklyUpdates = 'כמות עדכונים שבועי',
  DashboardCardTitleWarnings = 'כמות אזהרות',
  DashboardCardPercentageUp = 'עלייה של',
  DashboardCardPercentageDown = 'ירידה של',
  DashboardCardDocuments = 'קבלות',
  InventoryTableNewItem = 'מוצר חדש',
  InventoryTableDeleteSelectedItems = 'מחיקת מוצרים מסומנים',
  InventoryTableImportExcelFile = 'יבא קובץ אקסל',
  InventoryTablePaginatorTitle = `מציג {first} עד {last} מתוך {totalRecords} מוצרים`,
  InventoryTableTotalRecords = 'כמות מוצרים:',
  InventoryTableSearch = 'חיפוש...',
  GlobalIDTitle = 'מס׳ זיהוי',
  GlobalProductTitle = 'שם המוצר',
  GlobalAmountStocktitle = 'כמות במלאי',
  GlobalAmountBeforeWarningTitle = 'כמות לפני אזהרה',
  GlobalStatusTitle = 'סטטוס',
}
