export const enum Strings {
  SearchBarPlaceholder = 'חיפוש...(ניתן לחפש לפי שם המוצר, סוג המוצר)',
  UnitInInventory = "יח' במלאי:",
  UnitBeforeWarning = 'יח׳ לפני אזהרה:',
  NameOfItem = 'שם המוצר',
  DrawerItemHome = 'בית',
  DrawerItemProducts = 'מוצרים',
  DashboardCardTitleItems = 'מוצרים',
  DashboardCardTitleTotalInventory = 'סה״כ מלאי',
  DashboardCardTitleWeeklyUpdates = 'כמות עדכונים שבועי',
  DashboardCardTitleWarnings = 'כמות אזהרות',
  DashboardCardPercentageUp = 'עלייה של',
  DashboardCardPercentageDown = 'ירידה של',
  DashboardCardElectrialProducts = 'מוצרים חשמליים',
  DashboardCardDocuments = 'קבלות',
}
