name: deploy to AWS

on: [push]

jobs:
  deploy_source:
    name: Deploy validit backend to AWS!
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest

    env:
      CI: true
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: |
          npm i
          npm i -g serverless
